/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as CartRouteImport } from './routes/cart'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as MenuItemIdRouteImport } from './routes/menu.$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuItemIdRoute = MenuItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => MenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/bookings/': typeof BookingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/bookings': typeof BookingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/menu': typeof MenuRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/menu/$itemId': typeof MenuItemIdRoute
  '/bookings/': typeof BookingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/cart'
    | '/menu'
    | '/sitemap.xml'
    | '/bookings/$bookingId'
    | '/menu/$itemId'
    | '/bookings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/cart'
    | '/menu'
    | '/sitemap.xml'
    | '/bookings/$bookingId'
    | '/menu/$itemId'
    | '/bookings'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/cart'
    | '/menu'
    | '/sitemap.xml'
    | '/bookings/$bookingId'
    | '/menu/$itemId'
    | '/bookings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  CartRoute: typeof CartRoute
  MenuRoute: typeof MenuRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/$itemId': {
      id: '/menu/$itemId'
      path: '/$itemId'
      fullPath: '/menu/$itemId'
      preLoaderRoute: typeof MenuItemIdRouteImport
      parentRoute: typeof MenuRoute
    }
  }
}

interface MenuRouteChildren {
  MenuItemIdRoute: typeof MenuItemIdRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuItemIdRoute: MenuItemIdRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  CartRoute: CartRoute,
  MenuRoute: MenuRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
